ALTER TABLE orders ADD COLUMN IF NOT EXISTS current_lat DOUBLE PRECISION;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS current_lng DOUBLE PRECISION;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS location_updated_at TIMESTAMPTZ;
